require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
  - 'vendor/**/*'
  - 'db/**/*'
  - 'bin/**/*'
  - 'spec/**/*'
  - 'node_modules/**/*'
  - 'config/puma.rb'
  - 'config/spring.rb'
  - 'config/initializers/backtrace_silencers.rb'
  - 'config/boot.rb'
  - 'Rakefile'
  - 'config/initializers/filter_parameter_logging.rb'
  - 'test/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
