version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - psgl_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432 # 左がローカル、右がdockerのport番号

  web:
    build: .
    tty: true
    command: >
      sh -c "
        rails db:create && rails db:migrate && rails db:seed &&
        rm -f tmp/pids/server.pid &&
        yarn install
        ./bin/dev
      "

    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  psgl_data:
