import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  ISO8601Date: any;
  ISO8601DateTime: any;
};

/** Autogenerated input type of AddLabelToTask */
export type AddLabelToTaskInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  labelId: Scalars['ID'];
  taskId: Scalars['ID'];
};

/** Autogenerated return type of AddLabelToTask */
export type AddLabelToTaskPayload = {
  __typename?: 'AddLabelToTaskPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  taskLabel: TaskLabel;
};

/** Autogenerated input type of CreateLabel */
export type CreateLabelInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  name: Scalars['String'];
};

/** Autogenerated return type of CreateLabel */
export type CreateLabelPayload = {
  __typename?: 'CreateLabelPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  label: Label;
};

/** Autogenerated input type of CreateShareTask */
export type CreateShareTaskInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  taskId: Scalars['ID'];
  userId: Scalars['ID'];
};

/** Autogenerated return type of CreateShareTask */
export type CreateShareTaskPayload = {
  __typename?: 'CreateShareTaskPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  taskId: Scalars['ID'];
  userId: Scalars['ID'];
};

/** Autogenerated input type of CreateTask */
export type CreateTaskInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  params: TaskAttributes;
};

/** Autogenerated return type of CreateTask */
export type CreateTaskPayload = {
  __typename?: 'CreateTaskPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  task: Task;
};

/** Autogenerated input type of DeleteLabel */
export type DeleteLabelInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of DeleteLabel */
export type DeleteLabelPayload = {
  __typename?: 'DeleteLabelPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated input type of DeleteShareTask */
export type DeleteShareTaskInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  taskId: Scalars['ID'];
  userId: Scalars['ID'];
};

/** Autogenerated return type of DeleteShareTask */
export type DeleteShareTaskPayload = {
  __typename?: 'DeleteShareTaskPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  taskId: Scalars['ID'];
  userId: Scalars['ID'];
};

/** Autogenerated input type of DeleteTask */
export type DeleteTaskInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of DeleteTask */
export type DeleteTaskPayload = {
  __typename?: 'DeleteTaskPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
};

export type Label = {
  __typename?: 'Label';
  createdAt: Scalars['ISO8601DateTime'];
  id: Scalars['ID'];
  name: Scalars['String'];
  updatedAt: Scalars['ISO8601DateTime'];
  userId: Scalars['Int'];
};

export type Mutation = {
  __typename?: 'Mutation';
  addLabelToTask?: Maybe<AddLabelToTaskPayload>;
  createLabel?: Maybe<CreateLabelPayload>;
  createShareTask?: Maybe<CreateShareTaskPayload>;
  createTask?: Maybe<CreateTaskPayload>;
  deleteLabel?: Maybe<DeleteLabelPayload>;
  deleteShareTask?: Maybe<DeleteShareTaskPayload>;
  deleteTask?: Maybe<DeleteTaskPayload>;
  removeLabelFromTask?: Maybe<RemoveLabelFromTaskPayload>;
  signUp?: Maybe<SignUpPayload>;
  updateTask?: Maybe<UpdateTaskPayload>;
};


export type MutationAddLabelToTaskArgs = {
  input: AddLabelToTaskInput;
};


export type MutationCreateLabelArgs = {
  input: CreateLabelInput;
};


export type MutationCreateShareTaskArgs = {
  input: CreateShareTaskInput;
};


export type MutationCreateTaskArgs = {
  input: CreateTaskInput;
};


export type MutationDeleteLabelArgs = {
  input: DeleteLabelInput;
};


export type MutationDeleteShareTaskArgs = {
  input: DeleteShareTaskInput;
};


export type MutationDeleteTaskArgs = {
  input: DeleteTaskInput;
};


export type MutationRemoveLabelFromTaskArgs = {
  input: RemoveLabelFromTaskInput;
};


export type MutationSignUpArgs = {
  input: SignUpInput;
};


export type MutationUpdateTaskArgs = {
  input: UpdateTaskInput;
};

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['String']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['String']>;
};

export type Query = {
  __typename?: 'Query';
  labels: Array<Label>;
  shareTasks: TaskConnection;
  shareUsers: Array<User>;
  task: Task;
  tasks: TaskConnection;
  unaddedTaskLabels: Array<Label>;
  unshareUsers: Array<User>;
  users: Array<User>;
};


export type QueryShareTasksArgs = {
  after?: InputMaybe<Scalars['String']>;
  before?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  state?: InputMaybe<Scalars['String']>;
  title: Scalars['String'];
};


export type QueryShareUsersArgs = {
  id: Scalars['ID'];
};


export type QueryTaskArgs = {
  id: Scalars['ID'];
};


export type QueryTasksArgs = {
  after?: InputMaybe<Scalars['String']>;
  before?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  state?: InputMaybe<Scalars['String']>;
  title: Scalars['String'];
};


export type QueryUnaddedTaskLabelsArgs = {
  id: Scalars['ID'];
};


export type QueryUnshareUsersArgs = {
  id: Scalars['ID'];
};

/** Autogenerated input type of RemoveLabelFromTask */
export type RemoveLabelFromTaskInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  labelId: Scalars['ID'];
  taskId: Scalars['ID'];
};

/** Autogenerated return type of RemoveLabelFromTask */
export type RemoveLabelFromTaskPayload = {
  __typename?: 'RemoveLabelFromTaskPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  taskLabel: TaskLabel;
};

/** Autogenerated input type of SignUp */
export type SignUpInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  params: UserAttributes;
};

/** Autogenerated return type of SignUp */
export type SignUpPayload = {
  __typename?: 'SignUpPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

export type Task = {
  __typename?: 'Task';
  body?: Maybe<Scalars['String']>;
  createdAt: Scalars['ISO8601DateTime'];
  id: Scalars['ID'];
  labels: Array<Label>;
  limitOn?: Maybe<Scalars['ISO8601Date']>;
  state: TaskStateEnum;
  title: Scalars['String'];
  updatedAt: Scalars['ISO8601DateTime'];
  userId: Scalars['Int'];
};

export type TaskAttributes = {
  body?: InputMaybe<Scalars['String']>;
  limitOn?: InputMaybe<Scalars['String']>;
  state: TaskStateEnum;
  title: Scalars['String'];
};

/** The connection type for Task. */
export type TaskConnection = {
  __typename?: 'TaskConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<TaskEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Task>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type TaskEdge = {
  __typename?: 'TaskEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String'];
  /** The item at the end of the edge. */
  node?: Maybe<Task>;
};

export type TaskLabel = {
  __typename?: 'TaskLabel';
  createdAt: Scalars['ISO8601DateTime'];
  id: Scalars['ID'];
  labelId: Scalars['Int'];
  taskId: Scalars['Int'];
  updatedAt: Scalars['ISO8601DateTime'];
};

export enum TaskStateEnum {
  Finished = 'finished',
  Started = 'started',
  Unstarted = 'unstarted'
}

/** Autogenerated input type of UpdateTask */
export type UpdateTaskInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
  params: TaskAttributes;
};

/** Autogenerated return type of UpdateTask */
export type UpdateTaskPayload = {
  __typename?: 'UpdateTaskPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  task: Task;
};

export type User = {
  __typename?: 'User';
  createdAt: Scalars['ISO8601DateTime'];
  cryptedPassword?: Maybe<Scalars['String']>;
  email: Scalars['String'];
  id: Scalars['ID'];
  name: Scalars['String'];
  salt?: Maybe<Scalars['String']>;
  updatedAt: Scalars['ISO8601DateTime'];
};

export type UserAttributes = {
  email?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  password?: InputMaybe<Scalars['String']>;
  passwordConfirmation?: InputMaybe<Scalars['String']>;
};

export type AddLabelToTaskMutationVariables = Exact<{
  taskId: Scalars['ID'];
  labelId: Scalars['ID'];
}>;


export type AddLabelToTaskMutation = { __typename?: 'Mutation', addLabelToTask?: { __typename?: 'AddLabelToTaskPayload', taskLabel: { __typename?: 'TaskLabel', id: string } } | null };

export type CreateLabelMutationVariables = Exact<{
  name: Scalars['String'];
}>;


export type CreateLabelMutation = { __typename?: 'Mutation', createLabel?: { __typename?: 'CreateLabelPayload', label: { __typename?: 'Label', id: string, name: string } } | null };

export type CreateShareTaskMutationVariables = Exact<{
  userId: Scalars['ID'];
  taskId: Scalars['ID'];
}>;


export type CreateShareTaskMutation = { __typename?: 'Mutation', createShareTask?: { __typename?: 'CreateShareTaskPayload', userId: string, taskId: string } | null };

export type CreateTaskMutationVariables = Exact<{
  params: TaskAttributes;
}>;


export type CreateTaskMutation = { __typename?: 'Mutation', createTask?: { __typename?: 'CreateTaskPayload', task: { __typename?: 'Task', id: string, title: string, body?: string | null } } | null };

export type DeleteLabelMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type DeleteLabelMutation = { __typename?: 'Mutation', deleteLabel?: { __typename?: 'DeleteLabelPayload', id: string } | null };

export type DeleteShareTaskMutationVariables = Exact<{
  userId: Scalars['ID'];
  taskId: Scalars['ID'];
}>;


export type DeleteShareTaskMutation = { __typename?: 'Mutation', deleteShareTask?: { __typename?: 'DeleteShareTaskPayload', userId: string, taskId: string } | null };

export type DeleteTaskMutationVariables = Exact<{
  id: Scalars['ID'];
}>;


export type DeleteTaskMutation = { __typename?: 'Mutation', deleteTask?: { __typename?: 'DeleteTaskPayload', id: string } | null };

export type RemoveLabelFromTaskMutationVariables = Exact<{
  taskId: Scalars['ID'];
  labelId: Scalars['ID'];
}>;


export type RemoveLabelFromTaskMutation = { __typename?: 'Mutation', removeLabelFromTask?: { __typename?: 'RemoveLabelFromTaskPayload', taskLabel: { __typename?: 'TaskLabel', id: string } } | null };

export type SignUpMutationVariables = Exact<{
  params: UserAttributes;
}>;


export type SignUpMutation = { __typename?: 'Mutation', signUp?: { __typename?: 'SignUpPayload', user: { __typename?: 'User', id: string, name: string, email: string } } | null };

export type UpdateTaskMutationVariables = Exact<{
  id: Scalars['ID'];
  params: TaskAttributes;
}>;


export type UpdateTaskMutation = { __typename?: 'Mutation', updateTask?: { __typename?: 'UpdateTaskPayload', task: { __typename?: 'Task', id: string, title: string, body?: string | null, state: TaskStateEnum, limitOn?: any | null } } | null };

export type LabelsQueryVariables = Exact<{ [key: string]: never; }>;


export type LabelsQuery = { __typename?: 'Query', labels: Array<{ __typename?: 'Label', id: string, name: string }> };

export type ShareTasksQueryVariables = Exact<{
  title: Scalars['String'];
  state?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Int']>;
  after?: InputMaybe<Scalars['String']>;
}>;


export type ShareTasksQuery = { __typename?: 'Query', shareTasks: { __typename?: 'TaskConnection', edges?: Array<{ __typename?: 'TaskEdge', cursor: string, node?: { __typename?: 'Task', id: string, title: string, body?: string | null, state: TaskStateEnum, limitOn?: any | null } | null } | null> | null, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor?: string | null, endCursor?: string | null } } };

export type ShareUsersQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type ShareUsersQuery = { __typename?: 'Query', shareUsers: Array<{ __typename?: 'User', id: string, name: string }> };

export type TaskQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type TaskQuery = { __typename?: 'Query', task: { __typename?: 'Task', id: string, title: string, body?: string | null, state: TaskStateEnum, limitOn?: any | null, labels: Array<{ __typename?: 'Label', id: string, name: string }> } };

export type TasksQueryVariables = Exact<{
  title: Scalars['String'];
  state?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Int']>;
  after?: InputMaybe<Scalars['String']>;
}>;


export type TasksQuery = { __typename?: 'Query', tasks: { __typename?: 'TaskConnection', edges?: Array<{ __typename?: 'TaskEdge', cursor: string, node?: { __typename?: 'Task', id: string, title: string, body?: string | null, state: TaskStateEnum, limitOn?: any | null } | null } | null> | null, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor?: string | null, endCursor?: string | null } } };

export type UnaddedTaskLabelsQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type UnaddedTaskLabelsQuery = { __typename?: 'Query', unaddedTaskLabels: Array<{ __typename?: 'Label', id: string, name: string }> };

export type UnshareUsersQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type UnshareUsersQuery = { __typename?: 'Query', unshareUsers: Array<{ __typename?: 'User', id: string, name: string }> };

export type UsersQueryVariables = Exact<{ [key: string]: never; }>;


export type UsersQuery = { __typename?: 'Query', users: Array<{ __typename?: 'User', id: string, name: string, email: string }> };


export const AddLabelToTaskDocument = gql`
    mutation addLabelToTask($taskId: ID!, $labelId: ID!) {
  addLabelToTask(input: {taskId: $taskId, labelId: $labelId}) {
    taskLabel {
      id
    }
  }
}
    `;
export type AddLabelToTaskMutationFn = Apollo.MutationFunction<AddLabelToTaskMutation, AddLabelToTaskMutationVariables>;

/**
 * __useAddLabelToTaskMutation__
 *
 * To run a mutation, you first call `useAddLabelToTaskMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useAddLabelToTaskMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [addLabelToTaskMutation, { data, loading, error }] = useAddLabelToTaskMutation({
 *   variables: {
 *      taskId: // value for 'taskId'
 *      labelId: // value for 'labelId'
 *   },
 * });
 */
export function useAddLabelToTaskMutation(baseOptions?: Apollo.MutationHookOptions<AddLabelToTaskMutation, AddLabelToTaskMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<AddLabelToTaskMutation, AddLabelToTaskMutationVariables>(AddLabelToTaskDocument, options);
      }
export type AddLabelToTaskMutationHookResult = ReturnType<typeof useAddLabelToTaskMutation>;
export type AddLabelToTaskMutationResult = Apollo.MutationResult<AddLabelToTaskMutation>;
export type AddLabelToTaskMutationOptions = Apollo.BaseMutationOptions<AddLabelToTaskMutation, AddLabelToTaskMutationVariables>;
export const CreateLabelDocument = gql`
    mutation createLabel($name: String!) {
  createLabel(input: {name: $name}) {
    label {
      id
      name
    }
  }
}
    `;
export type CreateLabelMutationFn = Apollo.MutationFunction<CreateLabelMutation, CreateLabelMutationVariables>;

/**
 * __useCreateLabelMutation__
 *
 * To run a mutation, you first call `useCreateLabelMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateLabelMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createLabelMutation, { data, loading, error }] = useCreateLabelMutation({
 *   variables: {
 *      name: // value for 'name'
 *   },
 * });
 */
export function useCreateLabelMutation(baseOptions?: Apollo.MutationHookOptions<CreateLabelMutation, CreateLabelMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateLabelMutation, CreateLabelMutationVariables>(CreateLabelDocument, options);
      }
export type CreateLabelMutationHookResult = ReturnType<typeof useCreateLabelMutation>;
export type CreateLabelMutationResult = Apollo.MutationResult<CreateLabelMutation>;
export type CreateLabelMutationOptions = Apollo.BaseMutationOptions<CreateLabelMutation, CreateLabelMutationVariables>;
export const CreateShareTaskDocument = gql`
    mutation createShareTask($userId: ID!, $taskId: ID!) {
  createShareTask(input: {userId: $userId, taskId: $taskId}) {
    userId
    taskId
  }
}
    `;
export type CreateShareTaskMutationFn = Apollo.MutationFunction<CreateShareTaskMutation, CreateShareTaskMutationVariables>;

/**
 * __useCreateShareTaskMutation__
 *
 * To run a mutation, you first call `useCreateShareTaskMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateShareTaskMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createShareTaskMutation, { data, loading, error }] = useCreateShareTaskMutation({
 *   variables: {
 *      userId: // value for 'userId'
 *      taskId: // value for 'taskId'
 *   },
 * });
 */
export function useCreateShareTaskMutation(baseOptions?: Apollo.MutationHookOptions<CreateShareTaskMutation, CreateShareTaskMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateShareTaskMutation, CreateShareTaskMutationVariables>(CreateShareTaskDocument, options);
      }
export type CreateShareTaskMutationHookResult = ReturnType<typeof useCreateShareTaskMutation>;
export type CreateShareTaskMutationResult = Apollo.MutationResult<CreateShareTaskMutation>;
export type CreateShareTaskMutationOptions = Apollo.BaseMutationOptions<CreateShareTaskMutation, CreateShareTaskMutationVariables>;
export const CreateTaskDocument = gql`
    mutation createTask($params: TaskAttributes!) {
  createTask(input: {params: $params}) {
    task {
      id
      title
      body
    }
  }
}
    `;
export type CreateTaskMutationFn = Apollo.MutationFunction<CreateTaskMutation, CreateTaskMutationVariables>;

/**
 * __useCreateTaskMutation__
 *
 * To run a mutation, you first call `useCreateTaskMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateTaskMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createTaskMutation, { data, loading, error }] = useCreateTaskMutation({
 *   variables: {
 *      params: // value for 'params'
 *   },
 * });
 */
export function useCreateTaskMutation(baseOptions?: Apollo.MutationHookOptions<CreateTaskMutation, CreateTaskMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreateTaskMutation, CreateTaskMutationVariables>(CreateTaskDocument, options);
      }
export type CreateTaskMutationHookResult = ReturnType<typeof useCreateTaskMutation>;
export type CreateTaskMutationResult = Apollo.MutationResult<CreateTaskMutation>;
export type CreateTaskMutationOptions = Apollo.BaseMutationOptions<CreateTaskMutation, CreateTaskMutationVariables>;
export const DeleteLabelDocument = gql`
    mutation deleteLabel($id: ID!) {
  deleteLabel(input: {id: $id}) {
    id
  }
}
    `;
export type DeleteLabelMutationFn = Apollo.MutationFunction<DeleteLabelMutation, DeleteLabelMutationVariables>;

/**
 * __useDeleteLabelMutation__
 *
 * To run a mutation, you first call `useDeleteLabelMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteLabelMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteLabelMutation, { data, loading, error }] = useDeleteLabelMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useDeleteLabelMutation(baseOptions?: Apollo.MutationHookOptions<DeleteLabelMutation, DeleteLabelMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<DeleteLabelMutation, DeleteLabelMutationVariables>(DeleteLabelDocument, options);
      }
export type DeleteLabelMutationHookResult = ReturnType<typeof useDeleteLabelMutation>;
export type DeleteLabelMutationResult = Apollo.MutationResult<DeleteLabelMutation>;
export type DeleteLabelMutationOptions = Apollo.BaseMutationOptions<DeleteLabelMutation, DeleteLabelMutationVariables>;
export const DeleteShareTaskDocument = gql`
    mutation deleteShareTask($userId: ID!, $taskId: ID!) {
  deleteShareTask(input: {userId: $userId, taskId: $taskId}) {
    userId
    taskId
  }
}
    `;
export type DeleteShareTaskMutationFn = Apollo.MutationFunction<DeleteShareTaskMutation, DeleteShareTaskMutationVariables>;

/**
 * __useDeleteShareTaskMutation__
 *
 * To run a mutation, you first call `useDeleteShareTaskMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteShareTaskMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteShareTaskMutation, { data, loading, error }] = useDeleteShareTaskMutation({
 *   variables: {
 *      userId: // value for 'userId'
 *      taskId: // value for 'taskId'
 *   },
 * });
 */
export function useDeleteShareTaskMutation(baseOptions?: Apollo.MutationHookOptions<DeleteShareTaskMutation, DeleteShareTaskMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<DeleteShareTaskMutation, DeleteShareTaskMutationVariables>(DeleteShareTaskDocument, options);
      }
export type DeleteShareTaskMutationHookResult = ReturnType<typeof useDeleteShareTaskMutation>;
export type DeleteShareTaskMutationResult = Apollo.MutationResult<DeleteShareTaskMutation>;
export type DeleteShareTaskMutationOptions = Apollo.BaseMutationOptions<DeleteShareTaskMutation, DeleteShareTaskMutationVariables>;
export const DeleteTaskDocument = gql`
    mutation deleteTask($id: ID!) {
  deleteTask(input: {id: $id}) {
    id
  }
}
    `;
export type DeleteTaskMutationFn = Apollo.MutationFunction<DeleteTaskMutation, DeleteTaskMutationVariables>;

/**
 * __useDeleteTaskMutation__
 *
 * To run a mutation, you first call `useDeleteTaskMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteTaskMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteTaskMutation, { data, loading, error }] = useDeleteTaskMutation({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useDeleteTaskMutation(baseOptions?: Apollo.MutationHookOptions<DeleteTaskMutation, DeleteTaskMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<DeleteTaskMutation, DeleteTaskMutationVariables>(DeleteTaskDocument, options);
      }
export type DeleteTaskMutationHookResult = ReturnType<typeof useDeleteTaskMutation>;
export type DeleteTaskMutationResult = Apollo.MutationResult<DeleteTaskMutation>;
export type DeleteTaskMutationOptions = Apollo.BaseMutationOptions<DeleteTaskMutation, DeleteTaskMutationVariables>;
export const RemoveLabelFromTaskDocument = gql`
    mutation removeLabelFromTask($taskId: ID!, $labelId: ID!) {
  removeLabelFromTask(input: {taskId: $taskId, labelId: $labelId}) {
    taskLabel {
      id
    }
  }
}
    `;
export type RemoveLabelFromTaskMutationFn = Apollo.MutationFunction<RemoveLabelFromTaskMutation, RemoveLabelFromTaskMutationVariables>;

/**
 * __useRemoveLabelFromTaskMutation__
 *
 * To run a mutation, you first call `useRemoveLabelFromTaskMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useRemoveLabelFromTaskMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [removeLabelFromTaskMutation, { data, loading, error }] = useRemoveLabelFromTaskMutation({
 *   variables: {
 *      taskId: // value for 'taskId'
 *      labelId: // value for 'labelId'
 *   },
 * });
 */
export function useRemoveLabelFromTaskMutation(baseOptions?: Apollo.MutationHookOptions<RemoveLabelFromTaskMutation, RemoveLabelFromTaskMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<RemoveLabelFromTaskMutation, RemoveLabelFromTaskMutationVariables>(RemoveLabelFromTaskDocument, options);
      }
export type RemoveLabelFromTaskMutationHookResult = ReturnType<typeof useRemoveLabelFromTaskMutation>;
export type RemoveLabelFromTaskMutationResult = Apollo.MutationResult<RemoveLabelFromTaskMutation>;
export type RemoveLabelFromTaskMutationOptions = Apollo.BaseMutationOptions<RemoveLabelFromTaskMutation, RemoveLabelFromTaskMutationVariables>;
export const SignUpDocument = gql`
    mutation signUp($params: UserAttributes!) {
  signUp(input: {params: $params}) {
    user {
      id
      name
      email
    }
  }
}
    `;
export type SignUpMutationFn = Apollo.MutationFunction<SignUpMutation, SignUpMutationVariables>;

/**
 * __useSignUpMutation__
 *
 * To run a mutation, you first call `useSignUpMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSignUpMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [signUpMutation, { data, loading, error }] = useSignUpMutation({
 *   variables: {
 *      params: // value for 'params'
 *   },
 * });
 */
export function useSignUpMutation(baseOptions?: Apollo.MutationHookOptions<SignUpMutation, SignUpMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<SignUpMutation, SignUpMutationVariables>(SignUpDocument, options);
      }
export type SignUpMutationHookResult = ReturnType<typeof useSignUpMutation>;
export type SignUpMutationResult = Apollo.MutationResult<SignUpMutation>;
export type SignUpMutationOptions = Apollo.BaseMutationOptions<SignUpMutation, SignUpMutationVariables>;
export const UpdateTaskDocument = gql`
    mutation updateTask($id: ID!, $params: TaskAttributes!) {
  updateTask(input: {id: $id, params: $params}) {
    task {
      id
      title
      body
      state
      limitOn
    }
  }
}
    `;
export type UpdateTaskMutationFn = Apollo.MutationFunction<UpdateTaskMutation, UpdateTaskMutationVariables>;

/**
 * __useUpdateTaskMutation__
 *
 * To run a mutation, you first call `useUpdateTaskMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateTaskMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateTaskMutation, { data, loading, error }] = useUpdateTaskMutation({
 *   variables: {
 *      id: // value for 'id'
 *      params: // value for 'params'
 *   },
 * });
 */
export function useUpdateTaskMutation(baseOptions?: Apollo.MutationHookOptions<UpdateTaskMutation, UpdateTaskMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdateTaskMutation, UpdateTaskMutationVariables>(UpdateTaskDocument, options);
      }
export type UpdateTaskMutationHookResult = ReturnType<typeof useUpdateTaskMutation>;
export type UpdateTaskMutationResult = Apollo.MutationResult<UpdateTaskMutation>;
export type UpdateTaskMutationOptions = Apollo.BaseMutationOptions<UpdateTaskMutation, UpdateTaskMutationVariables>;
export const LabelsDocument = gql`
    query labels {
  labels {
    id
    name
  }
}
    `;

/**
 * __useLabelsQuery__
 *
 * To run a query within a React component, call `useLabelsQuery` and pass it any options that fit your needs.
 * When your component renders, `useLabelsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useLabelsQuery({
 *   variables: {
 *   },
 * });
 */
export function useLabelsQuery(baseOptions?: Apollo.QueryHookOptions<LabelsQuery, LabelsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<LabelsQuery, LabelsQueryVariables>(LabelsDocument, options);
      }
export function useLabelsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<LabelsQuery, LabelsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<LabelsQuery, LabelsQueryVariables>(LabelsDocument, options);
        }
export type LabelsQueryHookResult = ReturnType<typeof useLabelsQuery>;
export type LabelsLazyQueryHookResult = ReturnType<typeof useLabelsLazyQuery>;
export type LabelsQueryResult = Apollo.QueryResult<LabelsQuery, LabelsQueryVariables>;
export const ShareTasksDocument = gql`
    query shareTasks($title: String!, $state: String, $first: Int, $after: String) {
  shareTasks(title: $title, state: $state, first: $first, after: $after) {
    edges {
      cursor
      node {
        id
        title
        body
        state
        limitOn
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
    `;

/**
 * __useShareTasksQuery__
 *
 * To run a query within a React component, call `useShareTasksQuery` and pass it any options that fit your needs.
 * When your component renders, `useShareTasksQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useShareTasksQuery({
 *   variables: {
 *      title: // value for 'title'
 *      state: // value for 'state'
 *      first: // value for 'first'
 *      after: // value for 'after'
 *   },
 * });
 */
export function useShareTasksQuery(baseOptions: Apollo.QueryHookOptions<ShareTasksQuery, ShareTasksQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ShareTasksQuery, ShareTasksQueryVariables>(ShareTasksDocument, options);
      }
export function useShareTasksLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ShareTasksQuery, ShareTasksQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ShareTasksQuery, ShareTasksQueryVariables>(ShareTasksDocument, options);
        }
export type ShareTasksQueryHookResult = ReturnType<typeof useShareTasksQuery>;
export type ShareTasksLazyQueryHookResult = ReturnType<typeof useShareTasksLazyQuery>;
export type ShareTasksQueryResult = Apollo.QueryResult<ShareTasksQuery, ShareTasksQueryVariables>;
export const ShareUsersDocument = gql`
    query shareUsers($id: ID!) {
  shareUsers(id: $id) {
    id
    name
  }
}
    `;

/**
 * __useShareUsersQuery__
 *
 * To run a query within a React component, call `useShareUsersQuery` and pass it any options that fit your needs.
 * When your component renders, `useShareUsersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useShareUsersQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useShareUsersQuery(baseOptions: Apollo.QueryHookOptions<ShareUsersQuery, ShareUsersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ShareUsersQuery, ShareUsersQueryVariables>(ShareUsersDocument, options);
      }
export function useShareUsersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ShareUsersQuery, ShareUsersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ShareUsersQuery, ShareUsersQueryVariables>(ShareUsersDocument, options);
        }
export type ShareUsersQueryHookResult = ReturnType<typeof useShareUsersQuery>;
export type ShareUsersLazyQueryHookResult = ReturnType<typeof useShareUsersLazyQuery>;
export type ShareUsersQueryResult = Apollo.QueryResult<ShareUsersQuery, ShareUsersQueryVariables>;
export const TaskDocument = gql`
    query task($id: ID!) {
  task(id: $id) {
    id
    title
    body
    state
    limitOn
    labels {
      id
      name
    }
  }
}
    `;

/**
 * __useTaskQuery__
 *
 * To run a query within a React component, call `useTaskQuery` and pass it any options that fit your needs.
 * When your component renders, `useTaskQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useTaskQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useTaskQuery(baseOptions: Apollo.QueryHookOptions<TaskQuery, TaskQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<TaskQuery, TaskQueryVariables>(TaskDocument, options);
      }
export function useTaskLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<TaskQuery, TaskQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<TaskQuery, TaskQueryVariables>(TaskDocument, options);
        }
export type TaskQueryHookResult = ReturnType<typeof useTaskQuery>;
export type TaskLazyQueryHookResult = ReturnType<typeof useTaskLazyQuery>;
export type TaskQueryResult = Apollo.QueryResult<TaskQuery, TaskQueryVariables>;
export const TasksDocument = gql`
    query tasks($title: String!, $state: String, $first: Int, $after: String) {
  tasks(title: $title, state: $state, first: $first, after: $after) {
    edges {
      cursor
      node {
        id
        title
        body
        state
        limitOn
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
    `;

/**
 * __useTasksQuery__
 *
 * To run a query within a React component, call `useTasksQuery` and pass it any options that fit your needs.
 * When your component renders, `useTasksQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useTasksQuery({
 *   variables: {
 *      title: // value for 'title'
 *      state: // value for 'state'
 *      first: // value for 'first'
 *      after: // value for 'after'
 *   },
 * });
 */
export function useTasksQuery(baseOptions: Apollo.QueryHookOptions<TasksQuery, TasksQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<TasksQuery, TasksQueryVariables>(TasksDocument, options);
      }
export function useTasksLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<TasksQuery, TasksQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<TasksQuery, TasksQueryVariables>(TasksDocument, options);
        }
export type TasksQueryHookResult = ReturnType<typeof useTasksQuery>;
export type TasksLazyQueryHookResult = ReturnType<typeof useTasksLazyQuery>;
export type TasksQueryResult = Apollo.QueryResult<TasksQuery, TasksQueryVariables>;
export const UnaddedTaskLabelsDocument = gql`
    query unaddedTaskLabels($id: ID!) {
  unaddedTaskLabels(id: $id) {
    id
    name
  }
}
    `;

/**
 * __useUnaddedTaskLabelsQuery__
 *
 * To run a query within a React component, call `useUnaddedTaskLabelsQuery` and pass it any options that fit your needs.
 * When your component renders, `useUnaddedTaskLabelsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUnaddedTaskLabelsQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useUnaddedTaskLabelsQuery(baseOptions: Apollo.QueryHookOptions<UnaddedTaskLabelsQuery, UnaddedTaskLabelsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UnaddedTaskLabelsQuery, UnaddedTaskLabelsQueryVariables>(UnaddedTaskLabelsDocument, options);
      }
export function useUnaddedTaskLabelsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UnaddedTaskLabelsQuery, UnaddedTaskLabelsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UnaddedTaskLabelsQuery, UnaddedTaskLabelsQueryVariables>(UnaddedTaskLabelsDocument, options);
        }
export type UnaddedTaskLabelsQueryHookResult = ReturnType<typeof useUnaddedTaskLabelsQuery>;
export type UnaddedTaskLabelsLazyQueryHookResult = ReturnType<typeof useUnaddedTaskLabelsLazyQuery>;
export type UnaddedTaskLabelsQueryResult = Apollo.QueryResult<UnaddedTaskLabelsQuery, UnaddedTaskLabelsQueryVariables>;
export const UnshareUsersDocument = gql`
    query unshareUsers($id: ID!) {
  unshareUsers(id: $id) {
    id
    name
  }
}
    `;

/**
 * __useUnshareUsersQuery__
 *
 * To run a query within a React component, call `useUnshareUsersQuery` and pass it any options that fit your needs.
 * When your component renders, `useUnshareUsersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUnshareUsersQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useUnshareUsersQuery(baseOptions: Apollo.QueryHookOptions<UnshareUsersQuery, UnshareUsersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UnshareUsersQuery, UnshareUsersQueryVariables>(UnshareUsersDocument, options);
      }
export function useUnshareUsersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UnshareUsersQuery, UnshareUsersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UnshareUsersQuery, UnshareUsersQueryVariables>(UnshareUsersDocument, options);
        }
export type UnshareUsersQueryHookResult = ReturnType<typeof useUnshareUsersQuery>;
export type UnshareUsersLazyQueryHookResult = ReturnType<typeof useUnshareUsersLazyQuery>;
export type UnshareUsersQueryResult = Apollo.QueryResult<UnshareUsersQuery, UnshareUsersQueryVariables>;
export const UsersDocument = gql`
    query users {
  users {
    id
    name
    email
  }
}
    `;

/**
 * __useUsersQuery__
 *
 * To run a query within a React component, call `useUsersQuery` and pass it any options that fit your needs.
 * When your component renders, `useUsersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUsersQuery({
 *   variables: {
 *   },
 * });
 */
export function useUsersQuery(baseOptions?: Apollo.QueryHookOptions<UsersQuery, UsersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UsersQuery, UsersQueryVariables>(UsersDocument, options);
      }
export function useUsersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UsersQuery, UsersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UsersQuery, UsersQueryVariables>(UsersDocument, options);
        }
export type UsersQueryHookResult = ReturnType<typeof useUsersQuery>;
export type UsersLazyQueryHookResult = ReturnType<typeof useUsersLazyQuery>;
export type UsersQueryResult = Apollo.QueryResult<UsersQuery, UsersQueryVariables>;